/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import DB.ConnexionDB;
import DB.Parameter;
import DB.ResultSetTableModel;
import DB.db_connection;
import Entities.Reservation;
import static Forms.StructureClients.isNumeric;
import Services.ReservationServiceImplement;
import java.awt.Color;
import static java.awt.Color.green;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Radhi Mighri
 */
public class StructureReservation extends JFrame {
    ResultSet rs;
    db_connection db;
    Connection cn = ConnexionDB.getConnexion();
    


    /**
     * Creates new form StructureClients
     */
    public StructureReservation() {
         db = new db_connection(new Parameter().HOST_DB, new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB, new Parameter().IPHOST, new Parameter().PORT);
         initComponents();
         table();
        setUndecorated(true);
            }
    
 public void CBshowName(){
     	try {
                        String sql = "SELECT Nom,Prenom FROM `clients`";
                        Statement stat = cn.createStatement();
                        ResultSet rs = stat.executeQuery(sql);		
                        while(rs.next()){
                            ClientSelect.addItem(rs.getString(1)+" "+rs.getString(2));
                        }
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println(e.getMessage());

		}
 }
     
     public void table() {
        ReservationServiceImplement res = new ReservationServiceImplement();
        rs= res.getAllReservation();
        jTable1.setModel(new ResultSetTableModel(rs));
        CBshowName();
        resDate.setBackground(white);
        arrDate.setBackground(white);
        DepDate.setBackground(white);
        PersonNbr.setBackground(white);
    }
     void actualiser() {
        resDate.setText("");
        arrDate.setText("");
        DepDate.setText("");
        PersonNbr.setText("");
        table();
     }

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comrech = new javax.swing.JComboBox();
        txtrech = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        reftable = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        DepDate = new javax.swing.JTextField();
        PersonNbr = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        resDate = new javax.swing.JTextField();
        arrDate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        Addbtn = new javax.swing.JButton();
        Modifybtn = new javax.swing.JButton();
        Deletebtn = new javax.swing.JButton();
        Refreshbtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ClientSelect = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        ResDetailArea = new javax.swing.JTextArea();
        PrintBtn = new javax.swing.JButton();
        ShowFactureBtn = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        Exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clients Management Window");
        setBackground(new java.awt.Color(153, 153, 255));
        setExtendedState(50);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Reservation", "Reservation Date", "Arrival Date", "Departure Date", "Number of Person"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(0, 102, 102));
        jTable1.setPreferredSize(new java.awt.Dimension(1000, 560));
        jTable1.setSelectionBackground(new java.awt.Color(51, 51, 51));
        jTable1.setSelectionForeground(new java.awt.Color(0, 102, 102));
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel7.setBackground(new java.awt.Color(153, 255, 204));
        jLabel7.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabel7.setText("Reservations Management");

        jButton1.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id_res", "date_res", "arrival_date", "departure_date", "person_number" }));
        comrech.setAlignmentX(1.0F);
        comrech.setAlignmentY(5.0F);
        comrech.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        comrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comrechActionPerformed(evt);
            }
        });

        txtrech.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Searching by category");

        reftable.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        reftable.setText("Refresh");
        reftable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        reftable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reftableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtrech))
                                .addComponent(comrech, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(reftable, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comrech, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtrech, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reftable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(155, 155, 155))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 920, 240));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel5.setPreferredSize(new java.awt.Dimension(357, 47));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel9.setText("dep_date");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel14.setText("person Number");

        PersonNbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonNbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DepDate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonNbr, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonNbr, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel4.setPreferredSize(new java.awt.Dimension(357, 47));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel2.setText("date_res");

        arrDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrDateActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("arrival_date");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resDate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arrDate, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

        Addbtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });

        Modifybtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Modifybtn.setText("Modify");
        Modifybtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Modifybtn.setMaximumSize(new java.awt.Dimension(37, 29));
        Modifybtn.setMinimumSize(new java.awt.Dimension(37, 29));
        Modifybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifybtnActionPerformed(evt);
            }
        });

        Deletebtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Deletebtn.setText("Delete");
        Deletebtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Deletebtn.setMaximumSize(new java.awt.Dimension(37, 29));
        Deletebtn.setMinimumSize(new java.awt.Dimension(37, 29));
        Deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletebtnActionPerformed(evt);
            }
        });

        Refreshbtn.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Refreshbtn.setText("Refresh");
        Refreshbtn.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        Refreshbtn.setMaximumSize(new java.awt.Dimension(37, 29));
        Refreshbtn.setMinimumSize(new java.awt.Dimension(37, 29));
        Refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Refreshbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(Deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Modifybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Addbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Addbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Modifybtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Refreshbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel6.setPreferredSize(new java.awt.Dimension(357, 47));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel4.setText("Client");

        ClientSelect.setBackground(new java.awt.Color(204, 255, 204));
        ClientSelect.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ClientSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Client" }));
        ClientSelect.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ClientSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClientSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(ClientSelect, 0, 291, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ResDetailArea.setColumns(20);
        ResDetailArea.setRows(5);
        jScrollPane2.setViewportView(ResDetailArea);

        PrintBtn.setText("Print it");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });

        ShowFactureBtn.setText("Show Reservation");
        ShowFactureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowFactureBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ShowFactureBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PrintBtn)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrintBtn)
                    .addComponent(ShowFactureBtn))
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 920, 270));

        jPanel10.setBackground(new java.awt.Color(255, 0, 0));
        jPanel10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        Exit.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setText("X");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Exit.setInheritsPopupMenu(false);
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 610));

        setSize(new java.awt.Dimension(942, 596));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 
    private void comrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comrechActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        resDate.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 1)));
        arrDate.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2)));
        DepDate.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        PersonNbr.setText(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 4)));
        ClientSelect.setSelectedItem(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 5)));


        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtrech.getText().equals("")) {
            
            JOptionPane.showMessageDialog(this, "Field cannot be empty!");
        } else { 
            if (comrech.getSelectedItem().equals("id_res")) {
                ReservationServiceImplement res = new ReservationServiceImplement();
                rs= res.getAllReservationWhere("id_res LIKE '%" + txtrech.getText() + "%' ");
                jTable1.setModel(new ResultSetTableModel(rs));
            } else if (comrech.getSelectedItem().equals("date_res")) {
                ReservationServiceImplement res = new ReservationServiceImplement();
                rs= res.getAllReservationWhere("dateres LIKE '%" + txtrech.getText() + "%' ");
                jTable1.setModel(new ResultSetTableModel(rs));
            }
            else if (comrech.getSelectedItem().equals("arrival_date")) {                
                ReservationServiceImplement res = new ReservationServiceImplement();
                rs= res.getAllReservationWhere("datearr LIKE '%" + txtrech.getText() + "%' ");
                jTable1.setModel(new ResultSetTableModel(rs));           
            }
            else if (comrech.getSelectedItem().equals("departure_date")) {
                ReservationServiceImplement res = new ReservationServiceImplement();
                rs= res.getAllReservationWhere("datedep LIKE '%" + txtrech.getText() + "%' ");
                jTable1.setModel(new ResultSetTableModel(rs));          
            } 
            else if (comrech.getSelectedItem().equals("person_number")) {
                ReservationServiceImplement res = new ReservationServiceImplement();
                rs= res.getAllReservationWhere("nbrepersonne LIKE '%" + txtrech.getText() + "%' ");
                jTable1.setModel(new ResultSetTableModel(rs));           
            } 
            
        }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
       this.setVisible(false);
       System.out.println("Exit");
        
    }//GEN-LAST:event_ExitMouseClicked

    private void reftableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reftableActionPerformed
        table();
        txtrech.setText("");
    }//GEN-LAST:event_reftableActionPerformed

    private void ClientSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientSelectActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_ClientSelectActionPerformed

    private void RefreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshbtnActionPerformed

        actualiser();

    }//GEN-LAST:event_RefreshbtnActionPerformed

    private void DeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletebtnActionPerformed

        String id = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        if (JOptionPane.showConfirmDialog(this, "Are you sure ?", "attention!!!", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            ReservationServiceImplement res = new ReservationServiceImplement();
            res.delReservation(id);
            actualiser();

        } else {
            return;
        }

    }//GEN-LAST:event_DeletebtnActionPerformed

    private void ModifybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifybtnActionPerformed

        if (arrDate.getText().equals("") || resDate.getText().equals("") || DepDate.getText().equals("")
            || PersonNbr.getText().equals("") ) 
        {
            JOptionPane.showMessageDialog(this, "Please fill all the fields ! ");
                 DepDate.setBackground(red);
                 arrDate.setBackground(red);
                 resDate.setBackground(red);
                 PersonNbr.setBackground(red);  
                 ClientSelect.setBackground(red);
        }
          else if( isNumeric(PersonNbr.getText()) == false )
              {            JOptionPane.showMessageDialog(this, "Person number must be a numeric !!! ");
                           PersonNbr.setBackground(red);

              } 
            else if (ClientSelect.getSelectedItem()== "Choose Client"){
        JOptionPane.showMessageDialog(this, "Please select a Client!");
         ClientSelect.setBackground(red);

        }
        
        else {
            Date datearr = null;
            Date dateres = null;
            Date datedep = null;

    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd");

    String date1 = arrDate.getText();
    String date2 = resDate.getText();
    String date3 = DepDate.getText();

    try {
      datearr = simpleDateFormat.parse(date1);
      dateres = simpleDateFormat.parse(date2);
      datedep = simpleDateFormat.parse(date3);      
     if(datedep.compareTo(datearr)<0){
     JOptionPane.showMessageDialog(this, "Departure date must be later than the arrival one !");
                 DepDate.setBackground(red);
                 arrDate.setBackground(red);


}

     else if((datedep.compareTo(dateres)<0)){
         JOptionPane.showMessageDialog(this, "Departure date must be later than the reservation one !");
         DepDate.setBackground(red);
         resDate.setBackground(red);

     }
     
     else if((dateres.compareTo(datearr)>0)){
         JOptionPane.showMessageDialog(this, "Arrival date must be later than the reservation one !");
         resDate.setBackground(red);
         arrDate.setBackground(red);

     }

            else {         
            String id = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            Reservation r = new Reservation(null,date2,date1,date3,PersonNbr.getText(),ClientSelect.getSelectedItem().toString());
            ReservationServiceImplement fact = new ReservationServiceImplement();
            fact.EditReservation(r,id);
                table();
                 DepDate.setBackground(green);
                 arrDate.setBackground(green);
                 resDate.setBackground(green);
                 PersonNbr.setBackground(green);
           JOptionPane.showMessageDialog(this, "Reservation was updated with success");       } 
    } catch (ParseException e) {
              System.out.println("Errerrrrr");
     JOptionPane.showMessageDialog(this, "Please verify the dates format (DD/MM/YYYY) !");
    }

        }

    }//GEN-LAST:event_ModifybtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        if (arrDate.getText().equals("") || resDate.getText().equals("") || DepDate.getText().equals("")
            || PersonNbr.getText().equals("")  ) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields ! ");
                 DepDate.setBackground(red);
                 arrDate.setBackground(red);
                 resDate.setBackground(red);
                 PersonNbr.setBackground(red);   
                 ClientSelect.setBackground(red);
        }
         else if( isNumeric(PersonNbr.getText()) == false )
              {            JOptionPane.showMessageDialog(this, "Person number must be a numeric !!! ");
                           PersonNbr.setBackground(red);

              }
        else if (ClientSelect.getSelectedItem()== "Choose Client"){
        JOptionPane.showMessageDialog(this, "Please select a Client!");
         ClientSelect.setBackground(red);

        }
        else {
            Date datearr = null;
            Date dateres = null;
            Date datedep = null;

    SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy/MM/dd");

    String date1 = arrDate.getText();
    String date2 = resDate.getText();
    String date3 = DepDate.getText();

    try {
      datearr = simpleDateFormat.parse(date1);
      dateres = simpleDateFormat.parse(date2);
      datedep = simpleDateFormat.parse(date3); 
        
     if(datedep.compareTo(datearr)<0){
     JOptionPane.showMessageDialog(this, "Departure date must be later than the arrival one !");
                 DepDate.setBackground(red);
                 arrDate.setBackground(red);


}

     else if((datedep.compareTo(dateres)<0)){
         JOptionPane.showMessageDialog(this, "Departure date must be later than the reservation one !");
         DepDate.setBackground(red);
         resDate.setBackground(red);

     }
     
     else if((dateres.compareTo(datearr)>0)){
         JOptionPane.showMessageDialog(this, "Arrival date must be later than the reservation one !");
         resDate.setBackground(red);
         arrDate.setBackground(red);

     }

     else {
              
            Reservation r = new Reservation(null,date2,date1,date3,PersonNbr.getText(),ClientSelect.getSelectedItem().toString());
            ReservationServiceImplement res = new ReservationServiceImplement();
            res.addReservation(r);
            table();
                 DepDate.setBackground(green);
                 arrDate.setBackground(green);
                 resDate.setBackground(green);
                 PersonNbr.setBackground(green);
           JOptionPane.showMessageDialog(this, "Reservation was added with success");  


     }
    } catch (ParseException e) {
     JOptionPane.showMessageDialog(this, "Please verify the dates format (DD/MM/YYYY) !");
      System.out.println("Errerrrrr");
    }

        }

    }//GEN-LAST:event_AddbtnActionPerformed

    private void PersonNbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonNbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonNbrActionPerformed

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed

        try {
            ResDetailArea.print();
            jPanel1.setFocusable(false);
            
            // TODO add your handling code here:
        } catch (PrinterException ex) {
            Logger.getLogger(StructureReservation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void ShowFactureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowFactureBtnActionPerformed
    ResDetailArea.setText("\tWelcome To BeMy Guest Hotel\n\n\t          Reservation Details: \n\n" +
            "\nClient : \t\t\t"+ ClientSelect.getSelectedItem().toString()+
            "\n=================================================================\n"+
            "\nReservation Date: \t\t\t"+resDate.getText()+
            "\nArrival Date: \t\t\t\t"+ arrDate.getText()+
            "\nDeparture Date: \t\t\t"+DepDate.getText()+
            "\nNumber Person: \t\t\t"+ PersonNbr.getText()
            );
        

    }//GEN-LAST:event_ShowFactureBtnActionPerformed

    private void arrDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrDateActionPerformed

    


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StructureReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StructureReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StructureReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StructureReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StructureReservation().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JComboBox ClientSelect;
    private javax.swing.JButton Deletebtn;
    private javax.swing.JTextField DepDate;
    private javax.swing.JLabel Exit;
    private javax.swing.JButton Modifybtn;
    private javax.swing.JTextField PersonNbr;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JButton Refreshbtn;
    private javax.swing.JTextArea ResDetailArea;
    private javax.swing.JButton ShowFactureBtn;
    private javax.swing.JTextField arrDate;
    private javax.swing.JComboBox comrech;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton reftable;
    private javax.swing.JTextField resDate;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
}
